#!/bin/bash
# Add a whitespace-trimmed entry to the one-line-help.txt file
# and sort the one-line-help.txt.
#
# author: andreasl

printf -- '%s\n' "$*" | sed 's/^ *//g' >> "$ONE_LINE_HELP_FILE_PATH"
sort -u -o "$ONE_LINE_HELP_FILE_PATH" "$ONE_LINE_HELP_FILE_PATH"
