#!/bin/bash
# Prepend all filenames in a given directory with a date of the form `YYYY-MM-DD-`.
# Ignore files that already have a matching date string.
shopt -s extglob

cd "$1" || exit 1

today="$(date '+%Y-%m-%d')"
for file in !([0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]-*); do
    [[ -e "$file" ]] || break
    mv "$file" "${today}-${file}"
done
