#!/usr/bin/env bash
# Prepend all filenames in a given directory with today's date of the form `YYYY-MM-DD-`.
# Ignore files that already have a matching date string.
#
# Usage:
#
#   addates <DIR>
#
# Examples:
#
#   addates myfolder
#   addates .
#
# author: andreasl
shopt -s extglob

cd "$1" || exit 1

today="$(date '+%Y-%m-%d')"
for file in !([0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]-*); do
    [[ -e "$file" ]] || break
    mv "$file" "${today}-${file}"
done
