#!/bin/bash
# Convert a video file to chromecast-compatible format.
#
# Usage:
#
#   convert-to-chromecast <input-file> [<output-file>]
#
# author: andreasl

[ $# -lt 1 ] && { echo "Usage: ${0##*/} <input-file> [<output-file>]"; exit 1; }

in_file="$1"
out_file="${2-${in_file%.*}.m4v}"

time HandBrakeCLI --preset 'Chromecast 1080p60 Surround' --input "$in_file" --output "$out_file"

# if you get stutters or whatnot, try with less fps
# time HandBrakeCLI --preset 'Chromecast 1080p30 Surround' --input "$in_file" --output "$out_file"
