#!/bin/bash
# Convert a video file to chromecast-compatible format.
#
# Usage:
#
#   convert-to-chromecast <input-file> [<output-file>] [--30fps]
#
#
# Note:
#
#   If you get stutters when streaming to chromecast, try the --30fps option.
#
#
# author: andreasl

[ $# -lt 1 ] && { echo "Usage: ${0##*/} <input-file> [<output-file>] [--30fps]"; exit 1; }

in_file=
out_file=
fps=60
while [ "$#" -gt 0 ]; do
    case "$1" in
    --30fps|--30)
        fps=30
        ;;
    *)
        out_file="${in_file:+${1}}"
        in_file="${in_file:-${1}}"
        ;;
    esac
    shift
done

out_file="${out_file:-${in_file%.*}.m4v}"

set -x
time HandBrakeCLI --preset "Chromecast 1080p${fps} Surround" --input "$in_file" --output "$out_file"
