#!/usr/bin/env bash
# Delete trailing whitespaces from given files.
#
# Usage:
#
#   deltrail <FILE>...
#
# Examples:
#
#   deltrail notes.txt
#   deltrail src/*.py
#
# author: andreasl

if sed --version >/dev/null 2>&1; then
    # GNU sed
    sed_inplace=(-i)
else
    # BSD sed
    sed_inplace=(-i '')
fi

while [ "$#" -gt 0 ]; do
    grep -EHn --color=always '[[:space:]]+$' "$1"
    sed "${sed_inplace[@]}" -E 's/[[:space:]]+$//' "$1"
    shift
done
