#!/usr/bin/env bash
# Delete trailing whitespaces from given files.
#
# Usage:
#
#   deltrail <FILE>...
#
# Examples:
#
#   deltrail notes.txt
#   deltrail src/*.py
#
# author: andreasl

while [ "$#" -gt 0 ]; do
    grep -EHn --color=always '[[:space:]]+$' "$1"
    sed --in-place 's/[[:space:]]\+$//' "$1"
    shift
done
