#!/usr/bin/env bash
# Delete trailing whitespaces from given files.
#
# author: andreasl

while [ "$#" -gt 0 ]; do
    grep -EHn --color=always '[[:space:]]+$' "$1"
    sed --in-place 's/[[:space:]]\+$//' "$1"
    shift
done
