#!/usr/bin/env bash
# Download an m3u8 stream into a single .ts file named after the movie.
#
# Usage:
#
#   download-index-m3u8 <URL> <NAME>
#
# Examples:
#
#   download-index-m3u8 http://foo.bar/some.m3u8 my-movie
#
# author: andreasl

m3u8_url="$1"
movie_name="$2"

# Name the output *.ts so that ffmpeg writes a single file. An *.m3u8 output name would pick
# ffmpeg's HLS muxer instead, which chops the stream into hundreds of index<N>.ts segments
# that then have to be concatenated back together in numeric order.
download-m3u8 "$m3u8_url" "${movie_name}.ts"
