#!/usr/bin/env bash
# Simple self-made alternative implementation to the popular file-finding tool `fd`.
#
# Usage:
#
#   fd [-a] <SEARCHTERM>
#
# author: andreasl

if [ "$1" == '-a' ]; then
    shift
    find -L . -iname "*${*}*"
else
    find -L . -not -path '*/\.*' -iname "*${*}*"
fi
