#!/bin/bash
# find - find and select
# Select some of the output of find
# and open the according files in vim.
#
# author: andreasl

show_usage() {
    script_name="${0##*/}"

    msg="${script_name}\n"
    msg+="Select some of the output of find and open the according files in vim.\n"
    msg+="\n"
    msg+="Usage:\n"
    msg+="  ${script_name} <search-pattern>\n"
    msg+="\n"
    msg+="Examples:\n"
    msg+="  ${script_name} '.sh'            # find & select files whose names contain '.sh'\n"
    msg+="  ${script_name} 'stan getz'      # find & select files whose names contain 'stan getz'\n"
    msg+="  ${script_name} -h               # print the usage message\n"
    msg+="  ${script_name} --help           # print the usage message\n"
    printf "$msg"
}
if [[ "$1" =~ ^(-h|--help)$ ]] ; then
    show_usage
    exit 0
fi

selection="$(find -L . -iname "*${*}*" | fzf -m)"
if [ -n "$selection" ]; then
    vim -p $(printf "$selection")
fi
