#!/bin/bash
# Print paragraphs from the work journal that have the given hashtags.
#
# Usage:
#   hashtag <tag-name>  # list recent paragraphs with the given hashtag.
#   hashtag -l          # list all hashtags
#   hashtag --list      # list all hashtags
#
# Example:
#   hashtag retro       # list recent paragraphs with the hashtag 'retro'
#
# author: andreasl

filename="$JOURNAL_PATH"

if [[ $# -eq 0 ]] || [[ "$1" =~ ^(-l|--list)$ ]]; then
    # list hashtags
    hashtags="$(grep -Eio '  #[^ ]+([ ]+#[^ ]+)*$' "$filename")"
    # shellcheck disable=SC2086
    printf '%s\n' $hashtags | tr '[:upper:]' '[:lower:]' | sort -h | uniq
    exit 0
else
    # list recent notes to given hashtag, add blank lines between entries & limit the output
    tag="$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]')"
    awk -v RS= 'tolower($0) ~ /#'"${tag}"'/' "$filename" |
        sed 's/\(#[a-zA-Z0-9][a-zA-Z0-9]*\)$/\1\n/g' |
        tail -n 35
fi
