#!/bin/bash
# Print paragraphs from the work journal that have the given hashtags.
#
# Usage:
#   hashtag <tag-name>  # list recent paragraphs with the given hashtag.
#   hashtag -l          # list all hashtags
#   hashtag --list      # list all hashtags
#
# Example:
#   hashtag retro       # list recent paragraphs with the hashtag 'retro'
#
# author: andreasl

filename="${HOME}/Work/2020-Momox/journal.md"

if [[ $# -eq 0 ]] || [[ "$1" =~ ^(-l|--list)$ ]]; then
    # list hashtags
    hashtags="$(grep -Eio '  #[^ ]+([ ]+#[^ ]+)*$' "$filename")"
    printf '%s\n' $hashtags | sort -h | uniq
    exit 0
else
    # list recent notes to given hashtag, add blank lines between entries & limit the output
    awk -v RS= "/#${*}/" "$filename" | sed "s/\(#[a-zA-Z0-9][a-zA-Z0-9]*\)$/\1\n/g" | head -n 35
fi
