#!/usr/bin/env bash
# Convert given text to NATO alphabet.
#
# Usage:
#
#   nato <TEXT>...
#
# Examples:
#
#   nato hi there
#
# author: andreasl

# A case statement rather than an associative array, so this stays compatible
# with the Bash 3.2 that macOS ships.
to_nato() {
    case "$1" in
        [aA]) nato_char='Alfa' ;;
        [bB]) nato_char='Bravo' ;;
        [cC]) nato_char='Charlie' ;;
        [dD]) nato_char='Delta' ;;
        [eE]) nato_char='Echo' ;;
        [fF]) nato_char='Foxtrot' ;;
        [gG]) nato_char='Golf' ;;
        [hH]) nato_char='Hotel' ;;
        [iI]) nato_char='India' ;;
        [jJ]) nato_char='Juliett' ;;
        [kK]) nato_char='Kilo' ;;
        [lL]) nato_char='Lima' ;;
        [mM]) nato_char='Mike' ;;
        [nN]) nato_char='November' ;;
        [oO]) nato_char='Oscar' ;;
        [pP]) nato_char='Papa' ;;
        [qQ]) nato_char='Quebec' ;;
        [rR]) nato_char='Romeo' ;;
        [sS]) nato_char='Sierra' ;;
        [tT]) nato_char='Tango' ;;
        [uU]) nato_char='Uniform' ;;
        [vV]) nato_char='Victor' ;;
        [wW]) nato_char='Whiskey' ;;
        [xX]) nato_char='X-ray' ;;
        [yY]) nato_char='Yankee' ;;
        [zZ]) nato_char='Zulu' ;;
        1) nato_char='One' ;;
        2) nato_char='Two' ;;
        3) nato_char='Three' ;;
        4) nato_char='Four' ;;
        5) nato_char='Five' ;;
        6) nato_char='Six' ;;
        7) nato_char='Seven' ;;
        8) nato_char='Eight' ;;
        9) nato_char='Nine' ;;
        0) nato_char='Zero' ;;
        *) nato_char="$1" ;;
    esac
}

for word in "$@"; do
    out=()
    for ((i = 0; i < ${#word}; i++)); do
        to_nato "${word:i:1}"
        out+=("$nato_char")
    done
    printf "%s\n" "${out[*]}"
done
