#!/bin/bash
# Convert given text to NATO alphabet.

declare -A dict=(
    [a]="Alfa" [b]="Bravo" [c]="Charlie" [d]="Delta" [e]="Echo" [f]="Foxtrot"
    [g]="Golf" [h]="Hotel" [i]="India" [j]="Juliett" [k]="Kilo" [l]="Lima"
    [m]="Mike" [n]="November" [o]="Oscar" [p]="Papa" [q]="Quebec" [r]="Romeo"
    [s]="Sierra" [t]="Tango" [u]="Uniform" [v]="Victor" [w]="Whiskey"
    [x]="X-ray" [y]="Yankee" [z]="Zulu" [1]="One" [2]="Two" [3]="Three"
    [4]="Four" [5]="Five" [6]="Six" [7]="Seven" [8]="Eight" [9]="Nine" [0]="Zero"
)

for word in "$@"; do
    out=()
    for ((i = 0; i < ${#word}; i++)); do
        c="${word:i:1}"
        lower_c="${c,,}"
        if [[ -n "${dict[$lower_c]}" ]]; then
            out+=("${dict[$lower_c]}")
        else
            out+=("$c")
        fi
    done
    printf "%s\n" "${out[*]}"
done
