#!/usr/bin/env bash
# Iteratively grep for the given arguments in the file one-line-help.txt.
#
# Usage:
#
#   one-line-help [<TERM>...]
#
# Examples:
#
#   one-line-help                   # open the one-line-help file in vim
#   one-line-help docker images     # query the one-line-help for given terms; all terms must match
#
# author: andreasl

if [ "$#" -eq 0 ]; then
    vim -R "+call feedkeys('/')" "$ONE_LINE_HELP_FILE_PATH"  # -R readonly
else
    results="$(grep -i --color=never "$1" "$ONE_LINE_HELP_FILE_PATH")"
    for arg in "$@"; do
        results="$(printf -- '%s\n' "$results" | grep -i --color=never "$arg")"
    done
    printf -- '%s\n' "$results"
fi
