#!/usr/bin/env bash
# Print a given string a given number of times.
#
# Usage:
#
#   printn <TEXT> <COUNT>
#
# Examples:
#
#   printn '-' 10   # ----------
#   printn hello 3  # hellohellohello
#
# author: andreasl

for _ in $(seq "$2"); do
    printf '%s' "$1"
done
