#!/bin/bash
# Run a few ruff commands against a given file or directory.
#
# See:
# - https://docs.astral.sh/ruff/rules
#
# author: andreasl

file="${1:-.}"

ruff format "$file"
ruff check --select UP,ANN,B,C4,EXE,FA,ISC,ICN,LOG,G,PIE,Q,RSE,SIM,TC,I,NPY,W,FURB --ignore B905,UP015,UP035 --fix "$file"
ruff check --select I --fix "$file"  # imports
ruff check "$file"
