#!/usr/bin/env bash
# Get text from clipboard and transform certain charcaters to simpler ones and write the result back
# to the clipboard.
#
# author: andreasl

input_text="$(xclip -selection clipboard -out)"
if [ -z "$input_text" ]; then
    echo "Clipboard is empty or does not contain text."
    exit 1
fi

replace_chars() {
    sed \
        -e "s/[’‘]/'/g" \
        -e 's/[“”]/"/g' \
        -e 's/[„"]/"/g' \
        -e 's/[–—−‑‒]/-/g' \
        -e 's/[…]/.../g' \
        -e 's/[：]/:/g' \
        -e 's/[｜]/|/g' \
        -e 's|[⧸]|/|g' \
        -e 's|[＜]|<|g' \
        -e 's|[＞]|>|g' \
        -e 's/[​ ]//g'  # some invisible characters: <0x200b>, <0x202f>
}

remove_leading_and_trailing_blank_lines() {
    sed '/./,$!d; :a; /^[[:space:]]*$/{$d; N; ba}'
}

# Perform replacements
output_text="$(echo "$input_text" | replace_chars | remove_leading_and_trailing_blank_lines)"

# Update clipboard with modified text
printf '%s' "$output_text" | xclip -selection clipboard

echo "Special characters have been replaced and the clipboard has been updated."
