#!/usr/bin/env bash
# Iteratively grep for the given arguments in the tricks file.
#
# author: andreasl

if [ "$#" -eq 0 ]; then
    vim "+call feedkeys('/')" "$TRICKS_FILE_PATH"
else
    results="$(grep -i --color=never "$1" "$TRICKS_FILE_PATH")"
    for arg in "$@"; do
        results="$(printf -- '%s\n' "$results" | grep -i --color=never "$arg")"
    done
    printf -- '%s\n' "$results"
fi
